version: '3.7'
services:
  
  zipkin:
    build:
      context: zipkin
      dockerfile: Dockerfile
    ports:
      - 9411:9411
    restart: always
    networks:
      - micro-service-network
  
  eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    restart: always
    networks:
      - micro-service-network
    
  zuul:
    build:
      context: zuul
      dockerfile: Dockerfile
    ports:
      - 8762:8762
    restart: always
    depends_on:
      - eureka
      - zipkin
    networks:
      - micro-service-network
    
  result:
    build:
      context: result
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - eureka
      - zuul
      - zipkin
    networks:
      - micro-service-network
    
  query:
    build:
      context: query
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - zuul
      - eureka
      - result
      - zipkin
    networks:
      - micro-service-network
    
networks:
  micro-service-network:
